-- Ashfall enemies: what still crawls through the cinders.
return {
  {
    id = "cinderling",
    name = "Cinderling",
    desc = "A knot of embers that learned to want things.",
    behavior = "walker",
    shape = "blob",
    w = 13, h = 12,
    hp = 26, damage = 9, speed = 42,
    hops = true, hopVel = 250, hopRange = 70, hopCooldown = 1.5,
    aggroRange = 150,
    color = { 0.95, 0.45, 0.2 },
    eyeColor = { 1, 0.9, 0.5 },
    glow = 18,
    weight = 4,
  },
  {
    id = "ashmite",
    name = "Ashmite",
    desc = "Fast, hungry, and mostly teeth.",
    behavior = "walker",
    shape = "spikeball",
    w = 11, h = 11,
    hp = 16, damage = 7, speed = 74,
    aggroRange = 190,
    color = { 0.6, 0.5, 0.5 },
    weight = 3,
  },
  {
    id = "emberfly",
    name = "Emberfly",
    desc = "It circles twice. Then it doesn't circle.",
    behavior = "flyer",
    flying = true,
    shape = "wisp",
    w = 12, h = 12,
    hp = 18, damage = 8, speed = 60,
    dives = true, diveCooldown = 2.4, hoverHeight = 56,
    aggroRange = 200,
    color = { 1, 0.55, 0.25 },
    glow = 14,
    weight = 3,
  },
  {
    id = "pyre_totem",
    name = "Pyre Totem",
    desc = "Someone built it to keep the fire alive. It agreed.",
    behavior = "turret",
    shape = "totem",
    w = 12, h = 22,
    hp = 44, damage = 11, speed = 0,
    lob = true, shootCooldown = 2.3, telegraphTime = 0.55,
    aggroRange = 230,
    immovable = true,
    projectileColor = { 1, 0.5, 0.15 },
    color = { 0.55, 0.3, 0.22 },
    weight = 2,
  },
  {
    id = "soot_hulk",
    name = "Soot Hulk",
    desc = "The ash remembers being a wall. It charges like one.",
    behavior = "charger",
    shape = "husk",
    w = 20, h = 22,
    hp = 70, damage = 15, speed = 38,
    windupTime = 0.5, chargeTime = 0.9, chargeMult = 4.5, chargeCooldown = 2.2, stunTime = 1.0,
    aggroRange = 180,
    knockbackMult = 0.4,
    color = { 0.36, 0.3, 0.32 },
    weight = 2, minDepth = 2,
  },
}
