-- Deeper threats: enemies that appear across biomes at higher depths,
-- plus specialists that give fights more texture.
return {
  {
    id = "ash_hound",
    name = "Ash Hound",
    desc = "It remembers being loyal. To something else.",
    behavior = "charger",
    shape = "husk",
    w = 17, h = 13,
    hp = 34, damage = 11, speed = 66,
    windupTime = 0.35, chargeTime = 0.65, chargeMult = 4.2, chargeCooldown = 1.6, stunTime = 0.6,
    aggroRange = 210,
    color = { 0.55, 0.42, 0.38 },
    eyeColor = { 1, 0.6, 0.3 },
    weight = 2, minDepth = 3,
  },
  {
    id = "splitter",
    name = "Cinder Colony",
    desc = "One is three. Three are worse.",
    behavior = "walker",
    shape = "blob",
    w = 18, h = 16,
    hp = 52, damage = 10, speed = 34,
    aggroRange = 150,
    color = { 0.85, 0.5, 0.3 },
    glow = 16,
    splitsInto = { id = "cinderling", count = 2 },
    weight = 2, minDepth = 3,
  },
  {
    id = "mortar_shell",
    name = "Mortar Shell",
    desc = "A crab that swallowed a catapult. Or the reverse.",
    behavior = "turret",
    shape = "shell",
    w = 18, h = 13,
    hp = 50, damage = 13, speed = 0,
    lob = true, shootCooldown = 2.6, telegraphTime = 0.7,
    aggroRange = 260,
    knockbackMult = 0.3,
    projectileColor = { 1, 0.7, 0.3 },
    color = { 0.5, 0.42, 0.35 },
    weight = 2, minDepth = 4,
  },
  {
    id = "leech_wisp",
    name = "Leech Wisp",
    desc = "It doesn't hate you. It's just hungry for what you have left.",
    behavior = "floater",
    flying = true,
    shape = "wisp",
    w = 12, h = 12,
    hp = 26, damage = 9, speed = 44,
    aggroRange = 260,
    color = { 0.85, 0.3, 0.5 },
    glow = 18,
    noEyes = true,
    healsOnHit = 10,     -- heals itself when it touches you
    weight = 2, minDepth = 4,
  },
  {
    id = "warden_shield",
    name = "Shieldbearer",
    desc = "Someone must hold the line. It never asked why.",
    behavior = "walker",
    shape = "husk",
    w = 16, h = 20,
    hp = 66, damage = 12, speed = 30,
    armoredFront = true,
    aggroRange = 160,
    knockbackMult = 0.25,
    color = { 0.45, 0.48, 0.6 },
    eyeColor = { 0.7, 0.85, 1 },
    weight = 2, minDepth = 5,
  },
  {
    id = "ember_skirmisher",
    name = "Ember Skirmisher",
    desc = "Fights like it has somewhere better to be.",
    behavior = "flyer",
    flying = true,
    shape = "dervish",
    w = 13, h = 13,
    hp = 24, damage = 10, speed = 78,
    dives = true, diveCooldown = 1.6, hoverHeight = 44,
    aggroRange = 230,
    color = { 1, 0.6, 0.35 },
    glow = 14,
    weight = 2, minDepth = 5,
  },
}
