-- Duskmire enemies: things that grew in the wet dark.
return {
  {
    id = "bogshade",
    name = "Bogshade",
    desc = "It drifts through stone like regret through years.",
    behavior = "floater",
    flying = true,
    shape = "shade",
    w = 14, h = 16,
    hp = 30, damage = 10, speed = 34,
    aggroRange = 240,
    color = { 0.2, 0.45, 0.42 },
    eyeColor = { 0.5, 1, 0.85 },
    glow = 16,
    weight = 4,
  },
  {
    id = "spitter",
    name = "Marsh Spitter",
    desc = "Keeps its distance. Doesn't keep its saliva.",
    behavior = "turret",
    shape = "blob",
    w = 15, h = 13,
    hp = 28, damage = 10, speed = 0,
    lob = true, shootCooldown = 2.0, telegraphTime = 0.5,
    aggroRange = 210,
    projectileColor = { 0.5, 0.9, 0.4 },
    color = { 0.35, 0.55, 0.3 },
    weight = 3,
  },
  {
    id = "willowisp",
    name = "Willowisp",
    desc = "A lantern with opinions about who drowns tonight.",
    behavior = "orbiter",
    flying = true,
    shape = "wisp",
    w = 11, h = 11,
    hp = 22, damage = 8, speed = 40,
    orbitRadius = 36, orbitSpeed = 1.4,
    burstCount = 6, projectileSpeed = 105, shootCooldown = 2.8,
    aggroRange = 175,
    color = { 0.45, 0.95, 0.8 },
    glow = 20,
    noEyes = true,
    weight = 3,
  },
  {
    id = "shellback",
    name = "Shellback",
    desc = "Armored where it looks at you. Soft where it doesn't.",
    behavior = "walker",
    shape = "shell",
    w = 20, h = 14,
    hp = 58, damage = 12, speed = 26,
    armoredFront = true,
    aggroRange = 140,
    knockbackMult = 0.3,
    color = { 0.3, 0.5, 0.45 },
    weight = 2,
  },
  {
    id = "mire_maw",
    name = "Mire Maw",
    desc = "The puddle was never a puddle.",
    behavior = "walker",
    shape = "blob",
    w = 18, h = 12,
    hp = 46, damage = 13, speed = 52,
    hops = true, hopVel = 320, hopRange = 90, hopCooldown = 1.2,
    aggroRange = 170,
    color = { 0.15, 0.35, 0.3 },
    eyeColor = { 0.9, 1, 0.6 },
    weight = 2, minDepth = 2,
  },
}
