-- Hollow Spire enemies: the tower's immune system, still on duty.
return {
  {
    id = "sentinel",
    name = "Spire Sentinel",
    desc = "It has watched this hallway for three hundred years.",
    behavior = "flyer",
    flying = true,
    shape = "dervish",
    w = 14, h = 14,
    hp = 34, damage = 11, speed = 66,
    dives = true, diveCooldown = 2.0, hoverHeight = 48,
    aggroRange = 220,
    color = { 0.55, 0.5, 0.85 },
    eyeColor = { 1, 0.85, 0.4 },
    glow = 16,
    weight = 3,
  },
  {
    id = "warden_husk",
    name = "Warden Husk",
    desc = "The armor kept fighting after the warden stopped.",
    behavior = "charger",
    shape = "husk",
    w = 18, h = 24,
    hp = 80, damage = 16, speed = 42,
    windupTime = 0.42, chargeTime = 0.8, chargeMult = 5, chargeCooldown = 1.9, stunTime = 0.9,
    aggroRange = 200,
    knockbackMult = 0.35,
    color = { 0.4, 0.36, 0.6 },
    eyeColor = { 1, 0.8, 0.4 },
    weight = 3,
  },
  {
    id = "echo",
    name = "Echo",
    desc = "The Spire remembers its mages. Poorly. Dangerously.",
    behavior = "caster",
    flying = true,
    shape = "wisp",
    w = 13, h = 15,
    hp = 30, damage = 12, speed = 0,
    castTime = 0.75, shootCooldown = 3.0,
    aggroRange = 260,
    projectileColor = { 0.85, 0.6, 1 },
    color = { 0.7, 0.55, 0.95 },
    glow = 20,
    weight = 3,
  },
  {
    id = "dervish",
    name = "Blade Dervish",
    desc = "Six edges, no hesitation.",
    behavior = "walker",
    shape = "dervish",
    w = 13, h = 13,
    hp = 26, damage = 13, speed = 92,
    hops = true, hopVel = 300, hopRange = 80, hopCooldown = 0.9,
    aggroRange = 240,
    color = { 0.75, 0.7, 0.9 },
    weight = 3,
  },
  {
    id = "gilded_watcher",
    name = "Gilded Watcher",
    desc = "Gold was the only thing the Spire refused to let die.",
    behavior = "orbiter",
    flying = true,
    shape = "wisp",
    w = 12, h = 12,
    hp = 36, damage = 10, speed = 40,
    orbitRadius = 44, orbitSpeed = 1.1,
    burstCount = 8, projectileSpeed = 120, shootCooldown = 3.2,
    aggroRange = 190,
    projectileColor = { 1, 0.85, 0.4 },
    color = { 0.95, 0.8, 0.45 },
    glow = 22,
    noEyes = true,
    weight = 2, minDepth = 2,
  },
}
